version: "3"
services:
  web:
    image: docker-node-express-mongoapp
    build: ./
    command: node index.js
    ports:
      - 8080:3080
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"